import type { Metadata } from "next";
import { NextIntlClientProvider, Locale, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

//provider
import NextAuthProvider from "../../providers/NextAuthProvider";
import ReactQueryProvider from "../../providers/ReactQueryProvider";
import ReduxProvider from "../../providers/ReduxProvider";
import AppThemeProvider from "../../providers/ThemeProvider";
import { routing } from "../../i18n/routing";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider>
          <NextAuthProvider>
            <ReactQueryProvider>
              <ReduxProvider>
                <AppThemeProvider>{children}</AppThemeProvider>{" "}
              </ReduxProvider>
            </ReactQueryProvider>
          </NextAuthProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
